version: "3.8"

services:
  notification-db:
    image: postgres:15-alpine
    container_name: notification-db
    env_file: .env
    restart: unless-stopped
    ports:
      - "5443:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - notification-db-data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - patient-global-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  notification-service:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service
    env_file: .env
    restart: unless-stopped
    ports:
      - "8090:8090"
    depends_on:
      notification-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8090
      SPRING_DATASOURCE_URL: jdbc:postgresql://notification-db:5432/${POSTGRES_DB}?currentSchema=notification_schema&reWriteBatchedInserts=true
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PATIENT_SERVICE_URL: http://patient-management:8080
    volumes:
      - ./src:/app/src
    networks:
      - patient-global-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  notification-db-data:
    driver: local

networks:
  patient-global-network:
    external: true
