apiVersion: v1
kind: ConfigMap
metadata:
  name: patient-management-config
data:
  SERVER_PORT: "8080"
  GRPC_SERVER_PORT: "9090"
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_TOPIC_LAB_RESULT_COMPLETED: "lab-result-completed.v1"
  KAFKA_GROUP_PATIENT_LAB_RESULT: "patient-lab-result-group"
  KAFKA_TOPIC_USER_PROVISIONED: "user-provisioned.v1"
  KAFKA_GROUP_PATIENT_AUTH_LINK: "patient-auth-link-group"
  PATIENT_WRITE_DB_URL: "jdbc:postgresql://postgres:5432/patient_db?currentSchema=patient_schema&reWriteBatchedInserts=true"
  PATIENT_READ_DB_URL: "jdbc:postgresql://postgres:5432/patient_db?currentSchema=patient_schema"
