apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: patient-management-vault-store
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "patient-management-role"
          serviceAccountRef:
            name: patient-management-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: patient-management-vault-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: patient-management-vault-store
    kind: SecretStore
  target:
    name: patient-management-secret
    creationPolicy: Owner
  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: hospital/shared/jwt
        property: app_secret
    - secretKey: APP_SECURITY_ENCRYPTION_KEY
      remoteRef:
        key: hospital/patient-management/security
        property: encryption_key
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: hospital/patient-management/security
        property: encryption_key
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: hospital/patient-management/db
        property: username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: hospital/patient-management/db
        property: password
