apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: patient-management-netpol
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: patient-management
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # 1. API Gateway REST HTTP Trafiği
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: api-gateway
      ports:
        - protocol: TCP
          port: 8080
    # 2. Inter-service gRPC Trafiği (Sadece yetkili servisler)
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: appointment-service
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: admission-service
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: billing-service
      ports:
        - protocol: TCP
          port: 9090
    # 3. Prometheus Monitoring Trafiği
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 8080
  egress:
    # 1. CoreDNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # 2. Vault
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: vault
          podSelector:
            matchLabels:
              app.kubernetes.io/name: vault
      ports:
        - protocol: TCP
          port: 8200
    # 3. PostgreSQL Database (patient_db)
    - ports:
        - protocol: TCP
          port: 5432
    # 4. Kafka Event Bus
    - ports:
        - protocol: TCP
          port: 9092
