apiVersion: v1
kind: ServiceAccount
metadata:
  name: appointment-service-sa
  labels:
    app.kubernetes.io/name: appointment-service
    app.kubernetes.io/instance: appointment-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: hospital-information-system
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: false
