apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: auth-service-vault-store
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "auth-service-role"
          serviceAccountRef:
            name: auth-service-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-service-vault-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: auth-service-vault-store
    kind: SecretStore
  target:
    name: auth-service-secret
    creationPolicy: Owner
  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: hospital/shared/jwt
        property: app_secret
    - secretKey: JWT_SECRET
      remoteRef:
        key: hospital/shared/jwt
        property: app_secret
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: hospital/auth-service/db
        property: username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: hospital/auth-service/db
        property: password
    - secretKey: API_KEY
      remoteRef:
        key: hospital/auth-service/api-keys
        property: internal_api_key
