apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "auth_user"
  SPRING_DATASOURCE_PASSWORD: "CHANGE_ME"
  APP_SECRET: "CHANGE_ME_AT_LEAST_256_BITS"
  JWT_SECRET: "CHANGE_ME_JWT_SECRET"
  API_KEY: "CHANGE_ME"
