apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: billing-service-pdb
  labels:
    app.kubernetes.io/name: billing-service
    app.kubernetes.io/instance: billing-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: hospital-information-system
    app.kubernetes.io/managed-by: kustomize
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: billing-service
