apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: his

resources:
- ../../platform
- ../../base/apps/api-gateway
- ../../base/apps/auth-service



images:
- name: doguhannilt/admission-service
  newName: doguhannilt/admission-service
  newTag: sha-9188d7f
- name: doguhannilt/api-gateway
  newName: doguhannilt/api-gateway
  newTag: sha-9188d7f
- name: doguhannilt/auth-service
  newName: doguhannilt/auth-service
  newTag: sha-9188d7f
- name: doguhannilt/billing-service
  newName: doguhannilt/billing-service
  newTag: sha-9188d7f
- name: doguhannilt/doctor-service
  newName: doguhannilt/doctor-service
  newTag: sha-fc39548
- name: doguhannilt/notification-service
  newName: doguhannilt/notification-service
  newTag: sha-9188d7f
- name: doguhannilt/patient-management
  newName: doguhannilt/patient-management
  newTag: sha-fc39548
- name: doguhannilt/support-service
  newName: doguhannilt/support-service
  newTag: sha-9188d7f
