apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: his

resources:
  - ../../platform
  - ../../base/apps/api-gateway
  - ../../base/apps/auth-service



images:
  - name: doguhannilt/api-gateway
    newName: doguhannilt/api-gateway
    newTag: latest
  - name: doguhannilt/auth-service
    newName: doguhannilt/auth-service
    newTag: latest

