spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      acks: all
      properties:
        enable.idempotence: true

kafka:
  topic:
    replication-factor: 1
    partitions: 1
