apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/instance: notification-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: hospital-information-system
    app.kubernetes.io/managed-by: kustomize
data:
  SERVER_PORT: "8090"
  SPRING_DATASOURCE_WRITE_URL: "jdbc:postgresql://his-postgres:5432/notification_db?currentSchema=notification_schema&reWriteBatchedInserts=true"
  SPRING_DATASOURCE_READ_URL: "jdbc:postgresql://his-postgres:5432/notification_db?currentSchema=notification_schema&reWriteBatchedInserts=true"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  PATIENT_GRPC_ADDRESS: "static://patient-management:9090"
  PATIENT_SERVICE_URL: "http://patient-management:8080"
