apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: notification-service-vault-store
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/instance: notification-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: hospital-information-system
    app.kubernetes.io/managed-by: kustomize
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "notification-service-role"
          serviceAccountRef:
            name: notification-service-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notification-service-vault-secret
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/instance: notification-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: hospital-information-system
    app.kubernetes.io/managed-by: kustomize
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: notification-service-vault-store
    kind: SecretStore
  target:
    name: notification-service-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_WRITE_USERNAME
      remoteRef:
        key: hospital/notification-service/db
        property: username
    - secretKey: SPRING_DATASOURCE_WRITE_PASSWORD
      remoteRef:
        key: hospital/notification-service/db
        property: password
    - secretKey: SPRING_DATASOURCE_READ_USERNAME
      remoteRef:
        key: hospital/notification-service/db
        property: username
    - secretKey: SPRING_DATASOURCE_READ_PASSWORD
      remoteRef:
        key: hospital/notification-service/db
        property: password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: hospital/notification-service/redis
        property: password
    - secretKey: OPS_ALERT_EMAILS
      remoteRef:
        key: hospital/notification-service/api-keys
        property: ops_alert_emails
    - secretKey: APP_SECRET
      remoteRef:
        key: hospital/shared/jwt
        property: app_secret
    - secretKey: INTERNAL_SERVICE_TOKEN
      remoteRef:
        key: hospital/shared/internal-auth
        property: internal_token
