apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: notification-service-netpol
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/instance: notification-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: hospital-information-system
    app.kubernetes.io/managed-by: kustomize
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: notification-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: api-gateway
      ports:
        - protocol: TCP
          port: 8090
  egress:
    # 1. CoreDNS
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # 2. Vault
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: vault
      ports:
        - protocol: TCP
          port: 8200
    # 3. Patient Management (gRPC 9090 & HTTP 8080)
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: patient-management
      ports:
        - protocol: TCP
          port: 9090
        - protocol: TCP
          port: 8080
    # 4. Host Gateway (PostgreSQL, Kafka, Redis on 192.168.49.1)
    - to:
        - ipBlock:
            cidr: 192.168.49.1/32
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 9092
