apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notification-service-pdb
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/instance: notification-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: hospital-information-system
    app.kubernetes.io/managed-by: kustomize
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: notification-service
