apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-sa
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/instance: notification-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: hospital-information-system
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: true
