
services:
  # Isolated Write Database
  patient-write-db:
    image: postgres:15-alpine
    container_name: patient-write-db
    env_file: .env
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - patient-write-data:/var/lib/postgresql/data
      - ./init/write-schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - patient-global-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Isolated Read Database (CQRS Preparation)
  patient-read-db:
    image: postgres:15-alpine
    container_name: patient-read-db
    env_file: .env
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - patient-read-data:/var/lib/postgresql/data
      - ./init/read-schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - patient-global-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Patient Microservice
  patient-management:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patient-management
    env_file: .env
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      patient-write-db:
        condition: service_healthy
      patient-read-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8080
      SPRING_APPLICATION_JSON: '{"spring":{"datasource":{"write":{"jdbc-url":"jdbc:postgresql://patient-write-db:5432/${POSTGRES_DB}?currentSchema=patient_schema","username":"${POSTGRES_USER}","password":"${POSTGRES_PASSWORD}","driver-class-name":"org.postgresql.Driver"},"read":{"jdbc-url":"jdbc:postgresql://patient-read-db:5432/${POSTGRES_DB}?currentSchema=patient_schema","username":"${POSTGRES_USER}","password":"${POSTGRES_PASSWORD}","driver-class-name":"org.postgresql.Driver"}},"jpa":{"hibernate":{"ddl-auto":"update"}}}}'
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC_LAB_RESULT_COMPLETED: lab-result-completed.v1
      KAFKA_GROUP_PATIENT_LAB_RESULT: patient-lab-result-group
      APP_SECRET: ${APP_SECRET}
    volumes:
      - ./src:/app/src
    networks:
      - patient-global-network


volumes:
  patient-write-data:
    driver: local
  patient-read-data:
    driver: local

networks:
  patient-global-network:
    external: true