apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: api-gateway-vault-store
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "api-gateway-role"
          serviceAccountRef:
            name: api-gateway-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-gateway-vault-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: api-gateway-vault-store
    kind: SecretStore
  target:
    name: api-gateway-secret
    creationPolicy: Owner
  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: hospital/shared/jwt
        property: app_secret
