apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-gateway-netpol
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # 1. Ingress Controller Trafiği
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 4004
    # 2. Prometheus Monitoring Trafiği
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 4004
  egress:
    # 1. CoreDNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # 2. Vault
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: vault
          podSelector:
            matchLabels:
              app.kubernetes.io/name: vault
      ports:
        - protocol: TCP
          port: 8200
    # 3. Redis Rate Limiter
    - ports:
        - protocol: TCP
          port: 6379
    # 4. Kafka Audit Bus
    - ports:
        - protocol: TCP
          port: 9092
    # 5. Downstream Mikroservis Podları
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: patient-management
      ports:
        - protocol: TCP
          port: 8080
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: doctor-service
      ports:
        - protocol: TCP
          port: 8083
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: appointment-service
      ports:
        - protocol: TCP
          port: 8084
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: support-service
      ports:
        - protocol: TCP
          port: 8085
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: admission-service
      ports:
        - protocol: TCP
          port: 8086
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: auth-service
      ports:
        - protocol: TCP
          port: 8089
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: billing-service
      ports:
        - protocol: TCP
          port: 8081
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: notification-service
      ports:
        - protocol: TCP
          port: 8090
