apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-service-sa
  labels:
    app.kubernetes.io/name: admission-service
    app.kubernetes.io/instance: admission-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: hospital-information-system
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: false
