apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: his

resources:
  - ../../platform
  - ../../base/apps/api-gateway
  - ../../base/apps/auth-service
  - ../../base/ingress

