version: "3.8"

services:
  support-db:
    image: postgres:15-alpine
    container_name: support-db
    restart: unless-stopped
    ports:
      - "5442:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - support-db-data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - patient-global-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  support-service:
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 768M
        reservations:
          cpus: "0.5"
          memory: 512M
    build:
      context: ../
      dockerfile: support-service/Dockerfile
    container_name: support-service
    restart: unless-stopped
    ports:
      - "8085:8085"
    depends_on:
      support-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8085
      SPRING_DATASOURCE_URL: jdbc:postgresql://support-db:5432/${POSTGRES_DB}?currentSchema=support_schema&reWriteBatchedInserts=true
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC_LAB_ORDER_PLACED: lab-order-placed.v1
      KAFKA_TOPIC_LAB_RESULT_COMPLETED: lab-result-completed.v1
      KAFKA_TOPIC_INVENTORY_ITEM_CONSUMED: inventory-item-consumed.v1
      APP_SECRET: ${APP_SECRET}
    volumes:
      - ./src:/app/src
    networks:
      - patient-global-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  support-db-data:
    driver: local

networks:
  patient-global-network:
    external: true
