name: Support Service - DevSecOps CI/CD

on:
  push:
    branches: [ main, master ]
    paths:
      - 'support-service/**'
      - 'kubernetes/base/apps/support-service/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'support-service/**'
      - 'kubernetes/base/apps/support-service/**'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: support-service-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-service-ci.yml
    with:
      service_name: "support-service"
      service_path: "support-service"
      image_name: "doguhannilt/support-service"
      k8s_overlay_path: "kubernetes/overlays/prod"
    secrets: inherit
