apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: support-service-pdb
  labels:
    app.kubernetes.io/name: support-service
    app.kubernetes.io/instance: support-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: hospital-information-system
    app.kubernetes.io/managed-by: kustomize
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: support-service
